baseURL = 'https://traviole.netlify.app/'
languageCode = 'en-us'
title = 'Traviole/Travels'
theme = 'gallery'
copyright = 'All images under CC BY-NC-ND license'
timeout = '90s'
[params]
defaultTheme = 'dark'
