[build.environment]
HUGO_VERSION = "0.138.0"
HUGO_TIMEOUT = "90s"
TZ = "Europe/Zurich"
GIT_LFS_ENABLED = "true"

[build]
publish = "public"
command = """
convert -list font &&
find content/ -type f \\( -iname "*.jpg" -o -iname "*.jpeg" \\) -print -exec convert {} -font "DejaVu-Sans-Bold" -gravity SouthEast -pointsize 24 -stroke black -strokewidth 1 -fill "#fffdc3" -annotate +10+10 "CC BY-NC-ND Traviole" {} \\; &&
hugo --gc --minify && 
exiftool -r -gps:all= -xmp:geotag= public/
"""

[[plugins]]
package = "netlify-plugin-image-optim"
